usecase-beta
direction LR

actor Redacteur
actor Visiteur

Redacteur --> "ajouter une catégorie"
Redacteur --> "ajouter une article"
Redacteur --> "consulter les articles"
Redacteur --> "consulter les catégories"

Visiteur --> "consulter les articles"